name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.100'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish artifact
      run: dotnet publish -c Release -o publish
      working-directory: Solution

    - name: Archive artifact
      uses: actions/upload-artifact@v3
      with:
        name: KeyBlitz
        path: D:\a\KeyBlitz\KeyBlitz\Solution\publish


    - name: Download ILMerge
      run: |
        Invoke-WebRequest -Uri https://github.com/dotnet/ILMerge/releases/download/v3.0.37/ILMerge.zip -OutFile ILMerge.zip
        Expand-Archive -Path .\ILMerge.zip -DestinationPath ILMerge
  #    shell: PowerShell

    - name: Run ILMerge
      run: |
        .\ILMerge\ILMerge.exe /out:KeyBlitz.exe published\Solution.dll published\Solution.exe published\Solution.pdb published\Solution.runtimeconfig.json published\Solution.deps.json
   #   shell: PowerShell

    - name: Upload Merged .exe
      uses: actions/upload-artifact@v3
      with:
        name: merged-app
        path: KeyBlitz.exe

