name: .NET Core Desktop

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest 

    env:
      Solution_Name: Solution.sln
      Test_Project_Path: KeyBlitz.Tests\KeyBlitz.Tests.csproj 
      Appx_Bundle: Always
      Appx_Bundle_Platforms: "Any CPU"
      Appx_Package_Build_Mode: StoreUpload
      Configuration: Debug

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Install the .NET Core workload
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.100'

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release
  
    - name: Publish artifact
      run: dotnet publish -c Release -o publish
      working-directory: Solution

    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: your-project-artifact
        path: YourProjectName/publish
